# Generated by Django 2.2.2 on 2019-07-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together={('asset', 'macaddress', 'name')},
        ),
    ]
