# Generated by Django 2.2.2 on 2019-07-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0002_auto_20190717_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together={('asset', 'macaddress', 'model')},
        ),
    ]
