# Generated by Django 2.2.2 on 2019-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0003_auto_20190717_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='macaddress',
            field=models.CharField(max_length=64, verbose_name='MAC'),
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together={('asset', 'macaddress', 'name')},
        ),
    ]
